[project]
name = "minuet-bot"
version = "0.1.0"
description = "A script to monitor available lesson slots at the 'MINuET' driving school and send Telegram notifications"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
